### ISSUE TITLE
Models with the same structure

### ISSUE THREAD

**Issue by jpfairbanks** [jpfairbanks/SemanticModels.jl#103]
How do we talk about models that have the same structure? For example if I have two models that are both SIS but one is studying a virus in people and the other is a bacterial infection in dogs, then these models will have different units, and values, but otherwise have the same structure. We want to say that these models are "equivalent" because there is a morphism between their category representations. You replace `Quantity{Float, Human}` with `Quantity{Float, Dog}` and you can transform one model into the other. 

On the other hand if I take a second order linear ODE (hooke's law and the spring) and a first order nonlinear ODE, `f'(x) = -x/cos(x)` or something. These models are structurally different, and there is no pair of structure preserving maps going between them. 

How can we formalize and implement this in code?

1. given two models find a structure preserving map  (functor?) between them if it exists
2. develop types and functions for specifying "structure preserving transformations" on models and applying them.
3. If this structure on models is a Poset, meet and join in this poset would be really helpful.

**Comment by jpfairbanks** [comment]
We now have the typegraph datastructure available for answering this question. Agenttest2.jl shows that you can have 2 models with the same structure as models, with different typegraphs based on implementation choices. Can we create graph homomorphism between those two tyepgraphs that preserves the modeling structure.

**Comment by infvie** [comment]
How do we do that?

**Comment by jpfairbanks** [comment]
We need a function from vertices of the big graph `G, (u,v)` to vertices of the smaller graph `H, (a,b)` such that if `(u-> v) in E(G)` then` f(v) -> f(u) in E(H)`. I think we can do it by hand for the type graphs because they are so similar. The vast majority of vertices should just map to themselves.

**Comment by jpfairbanks** [comment]
Once we are satisfied with the exposition in #152 for this we can close this issue and open a new one for Phase 2 with a more general purpose graph homomorphism finding algorithm on typegraphs and dataflow graph.s
