### ISSUE TITLE
clustering vertices to merge them

### ISSUE THREAD

**Issue by jpfairbanks** [jpfairbanks/SemanticModels.jl#114]
@kuncao0228 is going to run an experiment about clustering the vertex labels in similar to #108 with a method like `UMAP.jl`. We want to see if clustering in the word2vec space can lead to a way to reconcile the knowledge graphs from multiple sources.

**Comment by jpfairbanks** [comment]
This will be presented as an example notebook showing the clustering results.

**Comment by kuncao0228** [comment]
Should have these up tonight got caught up on some stuff

**Comment by crherlihy** [comment]
See my comments on #97 and #114. I think if/when we close #114, we can close this issue as well.
