### ISSUE TITLE
Construct dataflow graph  for ingested .jl programs

### ISSUE THREAD

**Issue by crherlihy** [jpfairbanks/SemanticModels.jl#118]
Currently formalizing this as:

We want to ingest the main method of a program, and recursively enumerate: 

1. the set of subroutines, S = {s | s is called by main} that main calls
2.  the set of variables that main interacts with (as args, or in the form of locally scoped assignment statements), V = {v | v is passed to main, or is a local variable inside of main}
3. the set of sub-subroutines (e.g., subroutines called by each sub-routine called by main), $S_{sr}$ = {s.sr | s.sr called by s; $s \in S$}
4. the set of variables that the set of methods, $S$, interacts with, which may be global (w/respect to main) or local (w/respect to S) in scope, $V_{sr}$ = {s.sr.v | v is passed to an s.sr $\in S_{sr}$, or is a local variable inside of an s.sr $\in S_{sr}$}

We can extract the adjacency matrix from this graph and use this to assess co-occurrence; we'll probably want to think about a way to connect this graph to our type graph (join on symbols?)

**Comment by jpfairbanks** [comment]
Closed by #145
