### ISSUE TITLE
Update News for milestone 3 release (v0.2.0)

### ISSUE THREAD

**Issue by jpfairbanks** [jpfairbanks/SemanticModels.jl#123]
We need to update the news file with the latest changes.

**Comment by infvie** [comment]
What should go in the news? 

- [ ] shift in project from cassette to meta
- [ ] new examples 
- [ ] all model tool funcs? 

I am sure this list is missing stuff, but we should add them as checkboxes

**Comment by jpfairbanks** [comment]
yeah those things definitely need to go in. We still provide dubstep, so we don't need to highlight the fact that cassette isn't playing as big of a role as it used to. 

@infvie can you make a PR with the updated news file with those things listed out?
