### ISSUE TITLE
Include rendered notebook form of examples in the prebuilt docs

### ISSUE THREAD

**Issue by jpfairbanks** [jpfairbanks/SemanticModels.jl#130]
We need a way to make sure that people reading the docs can see the examples as rendered notebooks with their outputs.

jupytext is great for editing them, but we still need a way to distribute the rendered outputs for the docs.

**Comment by infvie** [comment]
How do we do this? do we include the fully run notebooks in the doc folder

**Comment by jpfairbanks** [comment]
We could include the fully run notebooks in the doc folder, but would still need a way to render them into HTML inside Documenter.jl

**Comment by jpfairbanks** [comment]
This package uses Weave.jl to make documenter compatible markdown files for the docs. https://github.com/Evizero/Augmentor.jl/blob/master/docs/exampleweaver.jl

**Comment by infvie** [comment]
Sounds good so we just need  run `ipython nbconvert --to HTML notebook.ipynb` for the whole directory and make sure they are in the right locations in the docs?

https://ipython.org/ipython-doc/3/notebook/nbconvert.html

**Comment by infvie** [comment]
Sorry, wifi was slow before second comment came through. I can take a stab at this.

**Comment by jpfairbanks** [comment]
That would be great, `jupytext --to markdown $f.jl && julia weave.jl $f.md` and then copying that `.jmd` file created by weave into the `docs/src/` folder would be good.

I don't know what the weave.jl script is but the docs provide instructions.

**Comment by jpfairbanks** [comment]
Here is an example of a weave script that we should be able to copy. https://github.com/JuliaDiffEq/DiffEqTutorials.jl/blob/master/src/DiffEqTutorials.jl we should just have to change the text in the templates and the header and footer.

**Comment by jpfairbanks** [comment]
Closed by #156
