### ISSUE TITLE
Fix odegraft.jl Example

### ISSUE THREAD

**Issue by mehalter** [jpfairbanks/SemanticModels.jl#159]
There is some sort of index out of bounds error on the `odegraft.jl` example. Could you figure out what it is? I am not familiar with the case/what would be the correct indexes.

**Comment by jpfairbanks** [comment]
Yeah I'll take a look this afternoon.

**Comment by jpfairbanks** [comment]
This bug is embarrassing. It is from a find and replace gone wrong.

when we refactored all the `AbstractProblem` subtypes to `AbstractModel` and did `s/Problem/Model/g` the following code broke.
```julia
function model(::Type{ExpODEProblem}, expr::Expr)
    matches = callsites(expr, :ODEProblem)
```
it should be 
```julia
function model(::Type{ExpODEModel}, expr::Expr)
    matches = callsites(expr, :ODEProblem)
```
