### ISSUE TITLE
Clean up validation code

### ISSUE THREAD

**Issue by jpfairbanks** [jpfairbanks/SemanticModels.jl#163]
@gallupBenRyan can you go through all the files related to validation and make sure they are in the right place and if they aren't necessary anymore, remove them?

**Comment by gallupBenRyan** [comment]
Sure thing. 

Are there any we want to stay, maybe in a different folder, as part of the future research around "DeepValidate?"

**Comment by jpfairbanks** [comment]
yeah go ahead and make a folder that has your best effort on the deep validate stuff. Write at the top of the files "WIP: work in progress on deepvalidate. This code is not expected to work at this time"
