### ISSUE TITLE
Deploy Eidos on production hardware 

### ISSUE THREAD

**Issue by jpfairbanks** [jpfairbanks/SemanticModels.jl#17]
@tgoodyear is setting up the Eidos webapp on prem.

Open Questions:
1. How do we change the port that it runs on?
2. Can we modify the rules without restarting the service?

**Comment by scottagt** [comment]
@jpfairbanks oh no, my intention wasn’t to suggest using the shell command line tool, just to communicate that I’ve come across an ability to reload grammars and then of course plug-in wherever it makes the most sense. :)
________________________________

**Comment by tgoodyear** [comment]
Sounds good, will do, thanks for finding.

Trevor

**Comment by jpfairbanks** [comment]
After our call with team Clulab, I think we should run the CLI app they wrote for us and put the output into a solr store.

PR pending with JSON output. https://github.com/ml4ai/automates/pull/6
