### ISSUE TITLE
Comparing Models: Matching vs Subgraphs

### ISSUE THREAD

**Issue by infvie** [jpfairbanks/SemanticModels.jl#185]
@jpfairbanks and I got into a discussion about how we could possibly do a matching problem to model the similarities between models instead of doing something like checking to see what is the largest sub-graph shared between two models.  These are some of the points of discussion:
- What would the sides be for the bipartite graph?
  - use the vars from model one vs the vars for model two and move through the other classes we define
  - represent types as S and functions as T and there is an edge from s in S to t in T if s is an argument to t? and an edge from t in T to s in S if t returns s as a return value

**Comment by jpfairbanks** [comment]
Let's take a step back and define the problem you want to solve, before we get into the details of techniques that can solve it. What do you mean by "model the similarities between models"?

**Comment by jpfairbanks** [comment]
We talked about this on the phone can came to the conclusion that we want to take a model and change it using the system to create a novel model. This way you never have to compare two extant models. And the systems should build transformations in such a way that the relationship between the old and new models is captured during the transformation process.
