### ISSUE TITLE
New API

### ISSUE THREAD

**Issue by infvie** [jpfairbanks/SemanticModels.jl#199]
This is an issue to discuss what our new API will look like and how the interactions will happen on the typegraph once extracted. One idea was implementing a DSL using the REPL environment directly using `ReplMaker.jl` 
### commands in the repl would be mapped under the hood as follows
```
julia>add_state(R)
julia>add_relation(R,dR,dS*omega)
julia>evaluate()
julia>reset()
``` 

```
m = add_state(m, :R)
m= addrelation(m, :R :dR, :(dS*omega))
eval(Expr(m))
```

**Comment by crherlihy** [comment]
Was just talking with @infvie about this issue, and wanted to post here that I think it's important in the api design we think about second-order/meta use cases. Eg., additive operations are necessary but not sufficient and what we're interested in defining are the class of operations that yield a closed set under some class models, as well as use cases that are about how we'd use the typegraph to resolve ambiguity/encourage inclusion of semantic information (or warnings about lack thereof) at compile time.

**Comment by infvie** [comment]
I put up a pull request with two possible apis for the find and replace. The main difference being the second is implemented as a DSL wrapper for DiffEqus.jl. Please let me know what other edits should be included

**Comment by jpfairbanks** [comment]
Closing as stale
