### ISSUE TITLE
IE Extraction Rules from Scripts using Cassette

### ISSUE THREAD

**Issue by scottagt** [jpfairbanks/SemanticModels.jl#22]
- Come up with initial list of extractions to use for Knowledge Graph

- List
  - Variables - e.g. i could be a variable, but is not a variable
  - Parameter -- e.g. "beta" is a parameter, is also a variable
  - Function Calls
  - Return Types

**Comment by scottagt** [comment]
Getting back from winter break and looking at this now

**Comment by jpfairbanks** [comment]
We ended up using Base.Meta.parse and writing rules against the AST to get information out. Cassette is better suited for injecting information into codes rather than getting information out of them.
