### ISSUE TITLE
Full SemanticModel Demonstration

### ISSUE THREAD

**Issue by mehalter** [jpfairbanks/SemanticModels.jl#220]
Combine the decorated cospan API with the PetriModel, ODEModel, RelationalOlog, and Schema decorations to show a full demonstration and use of the SemanticModels API to augment, validate, and solve a model.

Have an example where you can have a valid augmentation in the PetriModel and ODEModel decorations, but when the augmentation is applied to the RelationalOlog decoration you get an incompatible type error to illustrate simple model validation. Have another example where the model is valid in all decorations, and is therefore a valid domain specific model.

Decorate the model with a Schema to get a valid DB Schema that can hold data for the given PetriNet/ODE model.

Output knowledge graphs, DB Schema Diagrams, and executable ODE/PetriNet code.

**Comment by jpfairbanks** [comment]
This was demonstrated at the December Meeting.

[GTRI_milestone9_slides.pdf](https://github.com/jpfairbanks/SemanticModels.jl/files/4365700/GTRI_milestone9_slides.pdf)
[GTRI_milestone9_slides.pptx](https://github.com/jpfairbanks/SemanticModels.jl/files/4365702/GTRI_milestone9_slides.pptx)
