### ISSUE TITLE
Meta-Modeling Use Cases

### ISSUE THREAD

**Issue by scottagt** [jpfairbanks/SemanticModels.jl#23]
This issue is related to documenting a list of potential, planned, and excluded meta-modeling use cases based on available and unavailable resources:

### Unsorted

1. Scientist wants to integrate model variables (and potential parameters previously set to those variables) from another instance of a model from the same family e.g. SIR Paper 1 and SIR Paper 2
1.1 Scientist provides source code scripts using supported model libraries to system
1.2 System perform initial information extraction on scripts from both papers
1.3 System determines same variables shared across both models
1.4 System determines different variables within each model
1.5 System determines which variables can be integrated within a single model
1.6 Scientist selects which variables should be integrated
1.7 System uses a meta-model as a guide to create a new integrated model relying on variable inclusion/parameter setting information provided by meta-model
1.7 System validates the efficacy of the newly generated model based on different types ([cite]) of validation criteria
1.8 Scientist decide on whether to run new model and supplies required data

### Unsupported

**Comment by jpfairbanks** [comment]
See #16 for a place to add ideas as they crystalize. I think that use case planning will be a part of our next report.

**Comment by infvie** [comment]
I think for very general and common model set ups (e.g. SIR Models, Econometric Models, ect.) that we should include a collection of papers by default if the author doesn't want to build their own corpus of works. This could be a part of this project or live in their own repos which are called by our project. The idea that I am trying to get at is how there already data sets pre-loaded into many machine learning libraries for testing. Any thoughts on this or challenges that may arise?

**Comment by jpfairbanks** [comment]
Yeah we definitely want to have at least all the models from the EpiRecipes cookbook in a prepopulated collection of models. FluxML calls this a model zoo https://github.com/FluxML/model-zoo/ which has the demos and models you can build from. 

Right now these should be added to the `/examples/` folder in this repo. I think that is a good place to incubate them for now.
