### ISSUE TITLE
Updating to new Catlab version

### ISSUE THREAD

**Issue by jpfairbanks** [jpfairbanks/SemanticModels.jl#240]
SemanticModels has fallen really behind Catlab development. We need to bump that up to a modern version of Catlab.

**Comment by mehalter** [comment]
I'll take lead on this starting Monday. I have a really good understanding of the update (since I wrote most of them) and don't think it will be too much for me to do

**Comment by jpfairbanks** [comment]
👍, probably also a good time to clean up all our outstanding branches.
