### ISSUE TITLE
Translating EpiCookbook

### ISSUE THREAD

**Issue by infvie** [jpfairbanks/SemanticModels.jl#33]
This is going to be an issue space where Kun and I will be tracking progress on the translation of the Epi Cookbook from Julia v0.6 to Julia v1.0. We will be posting issues here when we need help.

**Comment by jpfairbanks** [comment]
Here is the tutorial for new Diffeq.jl http://docs.juliadiffeq.org/latest/tutorials/ode_example.html

**Comment by infvie** [comment]
![image](https://user-images.githubusercontent.com/41996797/51048235-70037d80-1598-11e9-8a8c-e5d7c807fadc.png)
@jpfairbanks There is still an option to use the macros to add the systems of equations vs adding a function. Do you think it would be better to have them formatted as functions of through this? I think that scientists would favor the function implementation and most code the model would see would take that form.

**Comment by jpfairbanks** [comment]
I think the function approach might be more popular, but its good to know that both options are available. There is also https://github.com/JuliaDiffEq/ModelingToolkit.jl which I think is the next generation version.

**Comment by infvie** [comment]
@jpfairbanks I think that we are good to close this issue now.

**Comment by jpfairbanks** [comment]
Let's make a PR to this repo that adds the updated notebooks in jupytext.jl format to the folder https://github.com/jpfairbanks/SemanticModels.jl/tree/master/examples/epicookbook and then we can close this. and #14

**Comment by kuncao0228** [comment]
@jpfairbanks created the PR

**Comment by jpfairbanks** [comment]
Link?

**Comment by kuncao0228** [comment]
@jpfairbanks 
https://github.com/jpfairbanks/epicookbook/pull/1
