### ISSUE TITLE
Definition and Concept Vertex Creation from Automates

### ISSUE THREAD

**Issue by scottagt** [jpfairbanks/SemanticModels.jl#34]
- [x] Create a Julia script that runs the automates system over a given directory of EpiRecipe cookbook files
From those outputs, create two kinds of edges:
- [x] Concept - Concept Name + Hash Value of definition text
- [x] Definition - long string text description associated with Concept
- [x] Create an edge from Concept to Definition: "is defined by"

**Comment by scottagt** [comment]
- Create a Julia script that runs the automates system over a given directory of EpiRecipe cookbook files
- From those outputs, create two kinds of edges:
 - Concept - Concept Name + Hash Value of definition text
 - Definition - long string text description associated with Concept
- Create an edge from Concept to Definition: "is defined by"

**Comment by scottagt** [comment]
So it turns out that the output files from automates still use the "cause" and "effect" syntax. I'm going to check if I can change that if we don't care about maintaining compatibility with our rules working in their existing web app.

- At the moment, the code I have assumes JSON output from is coded with cause/effect keys identified for concept and definition attributes
- Currently I'm using LightGraphs from the JuliaGraphs org on GitHub, not sure if this is what we're using in other areas; I haven't seen references to JuliaGraphs in other files from master just yet, so totally not committed to LightGraphs if there's a different JuliaGraph's project we want/should use

**Comment by scottagt** [comment]
Concerning running Automates (Scala code): 

There's a lot of dependencies that need to be installed for Scala to work with it and the run command loads a large set of JAR files that one would need to have installed. I'm wondering if it may be better that we run an Automates server and wrap an API around it and then send requests for parsing to it? @jpfairbanks thoughts? If we attempted to hard code a run command within definitions.jl there would likely need to be a reference to our separate project. It could be that we just specify that the user will need to ensure their copy of automates complies and they can just specify the class path to their automates dependency JARs and path to the ExtractAndExport Scala executable that we're leveraging.

At the moment we're loading the JSON output file and creating graphs from them.

**Comment by scottagt** [comment]
Looking at MetaGraphs, going to utilize that I think instead since it builds on LightGraphs, etc.

**Comment by jpfairbanks** [comment]
Closed by #36
