### ISSUE TITLE
Managing Corpora of Raw Text and Parsed JSONs

### ISSUE THREAD

**Issue by scottagt** [jpfairbanks/SemanticModels.jl#39]
> We should use something like DataDeps.jl Paper: https://arxiv.org/abs/1808.01091 for managing the corpus of raw text and the parsed jsons.

**Comment by scottagt** [comment]
That's so funny. I was just writing you in Slack about where to store KGs we create :)

**Comment by jpfairbanks** [comment]
Christine and were thinking of ways to store the KG, one way is to put a data creation script in a `.jl` file and then use `include(file.jl)`. This avoids the problem of picking a serialization format, but has security concerns. I think that having our API be "use a script to load data" and then we could write some scripts that use different formats.

**Comment by jpfairbanks** [comment]
The problem with that approach is that serializing into the script will be difficult.

**Comment by scottagt** [comment]
@jpfairbanks For this issue, do you want to put it on hold then? I created in reference to your comment at the end of #34 :
> We should use something like DataDeps.jl Paper: https://arxiv.org/abs/1808.01091 for managing the corpus of raw text and the parsed jsons.

**Comment by jpfairbanks** [comment]
@scottagt what is the path on box to the current version of the Automates output JSONs?

**Comment by scottagt** [comment]
The path to the input files is:
``/ASKE/Areas/Information Extraction/epireceipes_Automates_GTRI_ASKE_2rules_input``

The path to the output files is:
``/Users/scott/Box/ASKE/Areas/Information Extraction/epireceipes_Automates_GTRI_ASKE_2rules_output``

**Comment by scottagt** [comment]
The path to the input files is:
``/ASKE/Areas/Information Extraction/epireceipes_Automates_GTRI_ASKE_2rules_input``

The path to the output files is:
``ASKE/Areas/Information Extraction/epireceipes_Automates_GTRI_ASKE_2rules_output``

**Comment by jpfairbanks** [comment]
Data is available at aske.gtri.gatech.edu/data
