### ISSUE TITLE
Use Documenter.jl for documentation

### ISSUE THREAD

**Issue by jpfairbanks** [jpfairbanks/SemanticModels.jl#4]
We should use the documentation generator https://juliadocs.github.io/Documenter.jl/stable/man/guide/ for the docs in this package.

**Comment by jpfairbanks** [comment]
the last step is to enable publishing.

**Comment by jpfairbanks** [comment]
Our travis builds take longer than 10 minutes... which will make this hard.

**Comment by infvie** [comment]
Doc fixes : Intended Use Cases
- Intro
  - latex rendering issue?
- Answering Counterfactual
  - the numbering for this is off 
- Instrumenting Model Code
  - include Lotka-Volterra population dynamics latex

**Comment by infvie** [comment]
Doc fixes : Approaches
- almost none of the citations or hyperlinks are working :  why are none of these rendering? 
  - really bad in EpiModels Example
- Information Extraction
  - no talk of caching 
  - Personally, I feel one of the strongest points of this project is that we can store huge graphs locally, and scientist can easily use this pre-made corpus, but there is literally no mention of this.
- to me Data Sets in the Knowledge Graph makes more sense in the context of info extraction 
- The scheme.org section expresses/justifies why this project was started which is to fill a gap for what is not available currently => should be more in a "Why semanticmodels?" section - better story-boarding
- Types 
  - need to include cassette give them the  "bleeding edge of the bleeding edge of the bleeding edge" speech 
  - i dont feel like enough credit is given to the julia base with macros and exposure we have to lowered code

**Comment by infvie** [comment]
Doc fixes : dubstep
- Computer langs by nature are designed to be mnemonic
  - why were TraceCtx & LPCtx chosen? 
  - assumed knowledge of overdub

**Comment by infvie** [comment]
1. Collect a sample of known “good” inputs matched with their corresponding “good” outputs, and a sample of known “bad” inputs matched with their corresponding “bad” outputs.
    - “Good” here is defined as: given these input(s), the model output(s)/prediction(s) correspond to expected or observed empirical reality, within an acceptable tolerance/range re: error.
    -  Edge cases to note but not heavily consider @ this point:
        - For “good” input to “bad” output, we just corrupt the “good” inputs at various points along the computation.
        - If assumption that code is correct and does not contain bugs holds, then it is ok to assume we will not observe “bad” input to “good” output.
2. Run the simulation to collect a sample of known good outputs.
3. Instrument the code to log all SSA assignments from the function calls
4. Train an RNN on the sequence of [(func, var, val)...] where the labels are “good input/bad input”
    - By definition, any SSA “sentence” generated by a known “good” input is assumed to be “good”; thus, these labels essentially propagate down.
5. Partial evaluations of RNN give you the “where did it go wrong.
Instead of, 
![image](https://user-images.githubusercontent.com/41996797/52135972-0580b300-2615-11e9-8e10-ea23180a2ccc.png)
