### ISSUE TITLE
Extracting Comments from Jl Files for Automates Parsing

### ISSUE THREAD

**Issue by scottagt** [jpfairbanks/SemanticModels.jl#41]
- Create a Julia script to read Julia Source files and extract comments from them
- Comments begin with a \# sign

**Comment by jpfairbanks** [comment]
The scripts are currently in this folder https://github.com/jpfairbanks/epicookbook/tree/master/updatedJulia

**Comment by jpfairbanks** [comment]
1. Extract text from comments
2. Run through automates to get JSON
3. Run JSON through julia script to build MetaGraph.

**Comment by scottagt** [comment]
@jpfairbanks So this issue is just for extracting comments, not 2 or 3, just want to note that. I'm creating a different issue that can start based on those components :)
