### ISSUE TITLE
Finding more NLP rules

### ISSUE THREAD

**Issue by jpfairbanks** [jpfairbanks/SemanticModels.jl#51]
@infvie is going to work on collecting more knowledge elements from the cookbook text (beyond the definitions) and coming up with odin patterns that will find those knowledge elements.

The result should be captured in a CSV table similar to PR #15 `examples/knowledge_graph/relations.csv` is a goo place to store it.

**Comment by infvie** [comment]
@jpfairbanks when you say store in relations.csv do you mean just append that?

**Comment by scottagt** [comment]
@jpfairbanks this sounds like what I'm working on with the definitions but I can totally work on something else if you @infvie to pick it up, just let me know :)

**Comment by scottagt** [comment]
@jpfairbanks I'm about to commit some extraction code which grabs all the comment lines from a Julia file and all the parameters from a function and comes back with the intersection of the lines that match any of the parameters from the signatures.

**Comment by jpfairbanks** [comment]
@scottagt thanks for letting us know, before work got duplicated. Lets get what you have, as of now, posted as a PR so that @infvie can take a look and continue building on it.

**Comment by scottagt** [comment]
@jpfairbanks ok great; I'm testing right now and will be adding to the info_extract branch and make a PR off of that within the next hour I suspect

**Comment by jpfairbanks** [comment]
btw to answer the original question:
> @jpfairbanks when you say store in relations.csv do you mean just append that?

I meant to create a file `examples/epicookbook/relations.csv` for your manually extracted relations.

The CSV should have columns: `pageURL, originaltext, subject, verb, object`

**Comment by jpfairbanks** [comment]
Closed by https://github.com/jpfairbanks/SemanticModels.jl/tree/master/examples/knowledge_graph/manual
