### ISSUE TITLE
Develop algorithmic approach to reconcile/connect science and code vertices in KG

### ISSUE THREAD

**Issue by crherlihy** [jpfairbanks/SemanticModels.jl#64]

**Comment by crherlihy** [comment]
We will need to consider the following:

- [ ] schema harmonization w/respect to extraction from code vs. graph

- [ ] ensure that text parsers are parsing text rather than code (otherwise, our code types will end up pointing to concepts that are in fact from code rather than domain-specific texts)

- [ ] selection of reasonable defaults for types, text, and value field(s) upon insertion

- [ ] algorithm for determining whether a newly inserted vertex is semantically similar enough to an existing vertex (despite possible lexical differences) that we should skip insertion

**Comment by jpfairbanks** [comment]
This is being implemented by #114. We are going to use the variable names as text and embed them in the word2vec space with the concepts and then clustered along with them.

**Comment by crherlihy** [comment]
Clustering in the vector space is aligned with how we originally planned to handle this. I think we can close this issue out for now. Schema harmonization might still be helpful but is no longer a baseline expectation since our use-cases (and associated graphs) have splintered (e.g., we no longer expect a single, unified graph, but rather, can use ingested code/text to construct several different types of graphs; the graph selection will depend on the use case).
