### ISSUE TITLE
Installation instructions and testing

### ISSUE THREAD

**Issue by jpfairbanks** [jpfairbanks/SemanticModels.jl#68]
We need to bundle this software including a demo for DARPA to test. They suggested a jupyter notebook.

- [x] how to get julia installed (docker?)
- [x] what will go in notebook
- [x] how to test notebook (jupytext?)
- [x] how to bundle deps for easy install

**Comment by jpfairbanks** [comment]
@mehalter when you were testing the travis stuff, how did you do that? Did you make a docker container that built and ran everything? We should make a dockerhub image that installs all the dependencies and runs a jupyterlab instance. Then users can just run that and open the demo notebooks on their machines.

**Comment by mehalter** [comment]
I just forked to my personal github and enabled travis and did pushes there to test the travis stuff. I couldn't figure out a good way to do it locally and be able to test the `travis.yml` syntax. I can work on a docker image to install everything and spin up a jupyterlab instance.

**Comment by jpfairbanks** [comment]
yeah basically we want the deploy instructions for DARPA to be

1. `docker run -it -p8000:8000 -v/containerpath:$(pwd)/semanticmodels semanticmodels`
2. Open the browser to `localhost:8000`
3. Navigate to `examples/notebooks/example1.ipynb`
4. Run the cells

and the notebook `examples/notebooks/example1.ipynb` should be like

```julia
using SemanticModels
data = load("file")
result = process(data)
visualize(result)
```
so that basically the notebook just shows you how to use functions from the library to achieve some example goal. The current snippets in the documentation are good examples of what the notebooks should do.

**Comment by jpfairbanks** [comment]
@mehalter, are you correctly configured as a collaborator on https://cloud.docker.com/u/jpfa/repository/docker/jpfa/semanticmodels? Can you push the dockerfile to that repo?

**Comment by mehalter** [comment]
Looks good, I was able to push to the repo. Check it out by running
1. `docker run -it --rm -p 8888:8888 jpfa/semanticmodels:stretch`
2. Navigate to the link it returns `localhost:8888/?token=...`

Let me know if this looks like what you want.
