### ISSUE TITLE
Semantic Version oops

### ISSUE THREAD

**Issue by jpfairbanks** [jpfairbanks/SemanticModels.jl#78]
I called labeled everything v0.2 for the second milestone, but realized that is inconsistent with SemanticVersioning. So for now the docs are up at both aske.gtri.gatech.edu/v0.1 and aske.gtri.gatech.edu/v0.2. We will get the semver correct next time.

**Comment by crherlihy** [comment]
for reference: [https://semver.org/](https://semver.org/).
