### ISSUE TITLE
Make system architecture diagram linking formal representation -> KG -> use cases

### ISSUE THREAD

**Issue by crherlihy** [jpfairbanks/SemanticModels.jl#85]

**Comment by jpfairbanks** [comment]
Yes this is a good diagram to have. What do you have in mind?

1. Category theory for representing models at types/ologs/schemas 
2. Knowledge Representation with Graphs
3. Model usecases

How do you want to visualize the usecases? Like a drawing of pairs of models?

**Comment by crherlihy** [comment]
We also need to visualize this virtuous cycle:

> Our work is grounded in the belief that a framework which augments scientific workflows by alternately inferring, injecting, and rewarding the inclusion of semantic information in code via the type system can help to mitigate these challenges in a way that is computationally efficient, verifiable, reproducible, and open to improvement through iterative feedback and expansion with respect to domains.

**Comment by jpfairbanks** [comment]
@crherlihy do you still want to make this diagram? I can share the template I used for the examples/agentbased.jl models so we can match style with that. Otherwise graphviz is a good choice.

**Comment by crherlihy** [comment]
[aske_use_cases_v0.pptx](https://github.com/jpfairbanks/SemanticModels.jl/files/3021027/aske_use_cases_v0.pptx)
also posting in box. I can commit this if we think it's helpful, but the diffs won't be super meaningful.

**Comment by jpfairbanks** [comment]
This is great, I edited the box version and included it in the final report.
