### ISSUE TITLE
Extract text without code

### ISSUE THREAD

**Issue by jpfairbanks** [jpfairbanks/SemanticModels.jl#86]
We need a script in the /bin/ folder that extracts the text from a file, without the math and code. It should handle $\mu$ as "Mu".

**Comment by jpfairbanks** [comment]
We should handle subscripts as well.

**Comment by kuncao0228** [comment]
Sounds good I’ll try to have something by eod tomorrow

**Comment by kuncao0228** [comment]
https://github.com/kuncao0228/SemanticModels.jl/tree/master/bin

Hey James, 
I created a test, and utility for text extraction in the link above (testExtractTest.py & extractText.py). It currently handles equation removal as well as capitalization of variables. I want to add some additional tests/comments before the pull request.

**Comment by jpfairbanks** [comment]
That looks good so far, go ahead and make the PR so we can do in line comments. My first thought is that that this also needs to cut out markdown stuff like headers and code block syntax.


```md
# Header 1

This is some text, with some math $\alpha = \beta^2$.

This text also has code: 
    ```
    function foo(c)
        a,b = f(c)
        return b*a
    end
    ```
This code calculates the foo function.
``` 

Which should extract to

```
 Header 1

This is some text, with some math $\alpha = \beta^2$.

This text also has code: 

This code calculates the foo function.
```

**Comment by kuncao0228** [comment]
https://github.com/jpfairbanks/SemanticModels.jl/pull/88
created the pull here.

Yea that was going to be my next goal to take in the entire intro.md file. I wanted the script to essentially run as "python extractTest.py <file path>".

**Comment by kuncao0228** [comment]
"python extractTest.py _directoryPath_"*

**Comment by kuncao0228** [comment]
https://github.com/jpfairbanks/SemanticModels.jl/pull/88

Added to the original PR, creates output text file and ingests input files, fixes headers, added other filters

**Comment by jpfairbanks** [comment]
Once PR  #88 is closed we can close this issue
